// frontend/src/components/account-editor/EditorSidebar.tsx
"use client";

import { useMemo } from "react";
import type { EditorContentType, EditorEntrySummary, EditorSession } from "./types";
import { timeAgoLabel } from "./utils";

const TYPE_LABELS: Record<EditorContentType, string> = {
  article: "Статьи",
  news: "Новости",
  video: "Видео",
  gallery: "Галереи",
  homepage: "Главная",
};

const TYPE_ICONS: Record<EditorContentType, string> = {
  article: "📄",
  news: "✎",
  video: "🎬",
  gallery: "🖼",
  homepage: "🏠",
};

type EditorSidebarProps = {
  session: EditorSession | null;
  allowedTypes: EditorContentType[];
  items: Record<EditorContentType, EditorEntrySummary[]>;
  selectedType: EditorContentType;
  onSelectType: (type: EditorContentType) => void;
  onCreateNew: (type: EditorContentType) => void;
  onSelectItem: (type: EditorContentType, documentId: string) => void;
  query: string;
  onQueryChange: (value: string) => void;
  page: number;
  totalPages: number;
  onPageChange: (page: number) => void;
};

export function EditorSidebar({
  session,
  allowedTypes,
  items,
  selectedType,
  onSelectType,
  onCreateNew,
  onSelectItem,
  query,
  onQueryChange,
  page,
  totalPages,
  onPageChange,
}: EditorSidebarProps) {
  const normalizedQuery = query.trim().toLowerCase();
  const currentItems = useMemo(() => items[selectedType] ?? [], [items, selectedType]);
  const filteredItems = useMemo(() => {
    if (!normalizedQuery) {
      return currentItems;
    }
    return currentItems.filter((item) => item.title.toLowerCase().includes(normalizedQuery));
  }, [currentItems, normalizedQuery]);
  const itemsPerPage = 20;
  const startIndex = (page - 1) * itemsPerPage;
  const visibleItems = filteredItems.slice(startIndex, startIndex + itemsPerPage);

  return (
    <aside className="sticky top-14 h-[calc(100vh-3.5rem)] w-60 min-w-[15rem] overflow-y-auto border-r border-black/10 bg-[#f5f5f5] dark:border-white/10 dark:bg-[#1e1e1e]">
      <div className="flex items-center gap-3 border-b border-black/10 p-4 dark:border-white/10">
        <div className="flex h-9 w-9 items-center justify-center rounded-full bg-gradient-to-br from-[#1a4d2e] to-[#2d7a4f] text-sm font-semibold text-white dark:from-[#4ade80] dark:to-[#86efac] dark:text-black">
          {session?.user?.memberProfile?.displayName?.[0]?.toUpperCase() || session?.user?.username?.[0]?.toUpperCase() || "?"}
        </div>
        <div>
          <div className="text-sm font-semibold">{session?.user?.memberProfile?.displayName || session?.user?.username || "Пользователь"}</div>
          <div className="text-xs text-zinc-500 dark:text-zinc-400">
            Роль: {session?.user?.memberProfile?.accountType === "editor" ? "Редактор" : "Автор"}
          </div>
        </div>
      </div>

      <div className="px-3 pt-3">
        <div className="mb-2 px-2 text-[10px] font-bold uppercase tracking-wider text-zinc-500 dark:text-zinc-400">Тип материала</div>
        {allowedTypes.map((type) => {
          const count = items[type]?.length ?? 0;
          const isActive = type === selectedType;

          return (
            <button
              key={type}
              type="button"
              onClick={() => onSelectType(type)}
              className={`mb-1 flex w-full items-center gap-2 rounded px-3 py-2 text-sm transition-colors ${
                isActive
                  ? "bg-emerald-100 font-medium text-emerald-800 dark:bg-emerald-900/30 dark:text-emerald-200"
                  : "text-zinc-600 hover:bg-zinc-200 dark:text-zinc-300 dark:hover:bg-zinc-800"
              }`}
            >
              <span>{TYPE_ICONS[type]}</span>
              <span>{TYPE_LABELS[type]}</span>
              <span className={`ml-auto rounded px-1.5 py-0.5 text-[10px] ${isActive ? "bg-emerald-700 text-white dark:bg-emerald-500 dark:text-black" : "bg-zinc-200 text-zinc-600 dark:bg-zinc-700 dark:text-zinc-300"}`}>
                {count}
              </span>
            </button>
          );
        })}

        <button
          type="button"
          onClick={() => onCreateNew(selectedType)}
          className="mt-2 w-full rounded bg-[#1a4d2e] px-3 py-2 text-xs font-semibold text-white transition-colors hover:bg-[#2d7a4f] dark:bg-[#4ade80] dark:text-black dark:hover:bg-[#86efac]"
        >
          ＋ Новый материал
        </button>
      </div>

      <div className="px-3 pt-4">
        <div className="mb-2 px-2 text-[10px] font-bold uppercase tracking-wider text-zinc-500 dark:text-zinc-400">Все материалы</div>
        <input
          type="text"
          value={query}
          onChange={(event) => onQueryChange(event.target.value)}
          placeholder="Фильтр по заголовку..."
          className="mb-2 w-full rounded border border-black/10 bg-white px-3 py-1.5 text-xs outline-none focus:border-[#1a4d2e] dark:border-white/10 dark:bg-[#141414] dark:text-zinc-100"
        />

        <div className="space-y-1">
          {visibleItems.map((item) => (
            <button
              key={item.documentId}
              type="button"
              onClick={() => onSelectItem(selectedType, item.documentId)}
              className="w-full rounded p-2 text-left transition-colors hover:bg-zinc-200 dark:hover:bg-zinc-800"
            >
              <div className="truncate text-xs font-medium text-zinc-900 dark:text-zinc-100">{item.title}</div>
              <div className="mt-1 flex items-center gap-1.5 text-[10px] text-zinc-500 dark:text-zinc-400">
                <span className={`h-1.5 w-1.5 rounded-full ${item.status === "published" ? "bg-emerald-500" : "bg-amber-500"}`} />
                {item.status === "published" ? "Опубликовано" : "Черновик"}
                <span>·</span>
                <span>{timeAgoLabel(item.updatedAt || item.publishedAt)}</span>
              </div>
            </button>
          ))}
          {filteredItems.length === 0 ? (
            <div className="px-2 py-3 text-xs text-zinc-500 dark:text-zinc-400">Нет материалов</div>
          ) : null}
        </div>

        {totalPages > 1 ? (
          <div className="mt-2 flex items-center justify-between px-2 text-xs text-zinc-600 dark:text-zinc-400">
            <span>Стр. {page} из {totalPages}</span>
            <div className="flex gap-1">
              <button
                type="button"
                onClick={() => onPageChange(page - 1)}
                disabled={page === 1}
                className="rounded border border-black/10 px-2 py-1 transition-colors hover:bg-zinc-200 disabled:opacity-50 dark:border-white/10 dark:hover:bg-zinc-800"
              >
                ←
              </button>
              <button
                type="button"
                onClick={() => onPageChange(page + 1)}
                disabled={page === totalPages}
                className="rounded border border-black/10 px-2 py-1 transition-colors hover:bg-zinc-200 disabled:opacity-50 dark:border-white/10 dark:hover:bg-zinc-800"
              >
                →
              </button>
            </div>
          </div>
        ) : null}
      </div>
    </aside>
  );
}

// web/components/EditorSidebar.vue
<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue';

const props = defineProps<{ activeType?: string }>();
const emit = defineEmits<{
  (e: 'selectType', type: string): void;
  (e: 'selectMaterial', material: any): void;
  (e: 'newMaterial'): void;
}>();

const { user } = useAuth();
const { getEditorMaterials } = useApi();

const typeLabels: Record<string, { label: string; icon: string }> = {
  all: { label: 'Все материалы', icon: '📁' },
  article: { label: 'Статьи', icon: '📄' },
  news: { label: 'Новости', icon: '✎' },
  video: { label: 'Видео', icon: '🎬' },
  gallery: { label: 'Галереи', icon: '🖼' },
};

const typeOrder = ['all', 'article', 'news', 'video', 'gallery'];

const roleLabels: Record<string, string> = {
  admin: 'Администратор',
  editor: 'Редактор',
  author: 'Автор',
  member: 'Участник',
};

const search = ref('');
const materials = ref<any[]>([]);
const counts = ref<Record<string, number>>({});
const loading = ref(false);
const total = ref(0);
const page = ref(1);
const limit = 20;

const initials = computed(() => {
  const name = user.value?.displayName || user.value?.username || user.value?.email || '';
  return name
    .split(/\s+/)
    .map((p) => p[0])
    .slice(0, 2)
    .join('')
    .toUpperCase();
});

const totalPages = computed(() => Math.max(1, Math.ceil(total.value / limit)));

async function load() {
  loading.value = true;
  try {
    const query: Record<string, unknown> = {
      search: search.value || undefined,
      limit,
      offset: (page.value - 1) * limit,
    };
    if (props.activeType && props.activeType !== 'all') {
      query.type = props.activeType;
    }
    const res: any = await getEditorMaterials(query);
    materials.value = res.items || [];
    total.value = res.total || 0;
    const map: Record<string, number> = {};
    (res.counts || []).forEach((c: any) => {
      map[c.type] = c._count?.type || 0;
    });
    map.all = Object.values(map).reduce((sum: number, n) => sum + (typeof n === 'number' ? n : 0), 0);
    counts.value = map;
  } catch (e) {
    materials.value = [];
    total.value = 0;
  } finally {
    loading.value = false;
  }
}

function goToPage(newPage: number) {
  const target = Math.max(1, Math.min(totalPages.value, newPage));
  if (target !== page.value) {
    page.value = target;
    load();
  }
}

defineExpose({ load });

onMounted(load);
watch(() => props.activeType, () => {
  page.value = 1;
  load();
});
watch(search, () => {
  page.value = 1;
  // simple debounce could be added
  load();
});

const statusMeta: Record<string, { label: string; color: string }> = {
  draft: { label: 'Черновик', color: 'bg-orange-500' },
  in_review: { label: 'На проверке', color: 'bg-blue-500' },
  published: { label: 'Опубликовано', color: 'bg-accent' },
  rejected: { label: 'Отклонено', color: 'bg-red-600' },
};

function relativeTime(date: string) {
  const d = new Date(date);
  const now = new Date();
  const diff = Math.floor((now.getTime() - d.getTime()) / 1000);
  if (diff < 60) return 'только что';
  if (diff < 3600) return `${Math.floor(diff / 60)} мин назад`;
  if (diff < 86400) return `${Math.floor(diff / 3600)} ч назад`;
  if (diff < 2592000) return `${Math.floor(diff / 86400)} дн назад`;
  return d.toLocaleDateString('ru-RU');
}

function selectType(type: string) {
  emit('selectType', type);
}
</script>

<template>
  <aside class="flex h-full flex-col border border-foreground/10 bg-card">
    <!-- User -->
    <div class="flex items-center gap-3 border-b border-foreground/10 p-4">
      <div class="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-accent text-xs font-bold text-black">
        {{ initials }}
      </div>
      <div class="min-w-0">
        <div class="truncate text-sm font-semibold">
          {{ user?.displayName || user?.username || user?.email }}
        </div>
        <div class="text-xs text-foreground/50">
          Роль: {{ roleLabels[user?.role || 'member'] }}
        </div>
      </div>
    </div>

    <!-- Type list -->
    <div class="px-3 pt-3">
      <p class="px-2 text-[10px] font-bold uppercase tracking-wider text-foreground/40">
        Тип материала
      </p>
      <div class="mt-2 space-y-1">
        <button
          v-for="type in typeOrder"
          :key="type"
          class="flex w-full items-center gap-2 rounded px-2 py-1.5 text-left text-sm transition"
          :class="activeType === type ? 'bg-accent/10 text-accent' : 'text-foreground/70 hover:bg-foreground/5'"
          @click="selectType(type)"
        >
          <span>{{ typeLabels[type].icon }}</span>
          <span class="flex-1">{{ typeLabels[type].label }}</span>
          <span
            class="rounded px-1.5 py-0.5 text-[10px] font-semibold"
            :class="activeType === type ? 'bg-accent text-black' : 'bg-foreground/5 text-foreground/60'"
          >
            {{ counts[type] || 0 }}
          </span>
        </button>
      </div>
      <button
        class="mt-3 w-full rounded bg-accent px-3 py-2 text-sm font-semibold text-black transition hover:bg-accent/90"
        @click="emit('newMaterial')"
      >
        ＋ Новый материал
      </button>
    </div>

    <!-- Recent materials -->
    <div class="flex min-h-0 flex-1 flex-col border-t border-foreground/10 mt-4">
      <p class="px-5 pt-3 pb-2 text-[10px] font-bold uppercase tracking-wider text-foreground/40">
        Все материалы
      </p>
      <div class="px-4 pb-2">
        <input
          v-model="search"
          type="text"
          placeholder="Фильтр по заголовку..."
          class="w-full border border-foreground/10 bg-card px-3 py-1.5 text-xs outline-none focus:border-accent"
        >
      </div>
      <div class="flex-1 overflow-y-auto px-3 pb-3">
        <div v-if="loading" class="px-2 py-4 text-xs text-foreground/50">Загрузка…</div>
        <div v-else-if="!materials.length" class="px-2 py-4 text-xs text-foreground/50">
          Нет материалов
        </div>
        <div v-else class="space-y-1">
          <button
            v-for="item in materials"
            :key="item.id"
            class="w-full rounded px-2 py-2 text-left transition hover:bg-foreground/5"
            @click="emit('selectMaterial', item)"
          >
            <div class="truncate text-xs font-medium leading-tight">
              {{ item.title }}
            </div>
            <div class="mt-1 flex items-center gap-1.5 text-[10px] text-foreground/50">
              <span class="h-1.5 w-1.5 rounded-full" :class="statusMeta[item.status]?.color || 'bg-gray-400'" />
              <span>{{ statusMeta[item.status]?.label || item.status }}</span>
              <span>·</span>
              <span>{{ relativeTime(item.updatedAt) }}</span>
            </div>
          </button>
        </div>
        <!-- Pagination -->
        <div v-if="totalPages > 1" class="mt-2 flex items-center justify-between border-t border-foreground/10 px-2 pt-2">
          <button
            class="px-2 py-1 text-xs text-foreground/70 transition hover:text-foreground disabled:opacity-40"
            :disabled="page <= 1"
            @click="goToPage(page - 1)"
          >
            ← Назад
          </button>
          <span class="text-[10px] text-foreground/50">
            {{ page }} / {{ totalPages }}
          </span>
          <button
            class="px-2 py-1 text-xs text-foreground/70 transition hover:text-foreground disabled:opacity-40"
            :disabled="page >= totalPages"
            @click="goToPage(page + 1)"
          >
            Вперёд →
          </button>
        </div>
      </div>
    </div>
  </aside>
</template>
